### ISSUE TITLE
按readme和教程指引无法跑layoutlmv3版面模型，yolo可以，报错如下

### ISSUE THREAD

**Issue by Icefr09** [opendatalab/PDF-Extract-Kit#146]
Traceback (most recent call last):
  File "/data/pdf-extract-kit-1.0/scripts/layout_detection.py", line 41, in <module>
    main(args.config)
  File "/data/pdf-extract-kit-1.0/scripts/layout_detection.py", line 20, in main
    task_instances = initialize_tasks_and_models(config)
  File "/data/pdf-extract-kit-1.0/scripts/../pdf_extract_kit/utils/config_loader.py", line 40, in initialize_tasks_and_models
    ModelClass = MODEL_REGISTRY.get(model_name)
  File "/data/pdf-extract-kit-1.0/scripts/../pdf_extract_kit/registry/registry.py", line 15, in get
    raise ValueError(f"Item {name} not found in registry.")
ValueError: Item layout_detection_layoutlmv3 not found in registry.

**Comment by wangbinDL** [comment]
@Icefr09 
最新教程已更新：
需要（1）安装detectron2并（2）打开LayoutLMv3代码注释，具体教程请参考 https://pdf-extract-kit.readthedocs.io/zh-cn/latest/algorithm/layout_detection.html
