### ISSUE TITLE
pdf转markdown报错

### ISSUE THREAD

**Issue by miludedeng** [opendatalab/PDF-Extract-Kit#183]
python project/pdf2markdown/scripts/run_project.py --config project/pdf2markdown/configs/pdf2markdown.yaml

⚠️ GitHub assets check failure for https://api.github.com/repos/doclayout_yolo/assets/releases/tags/v8.1.0: 404 Not Found
⚠️ GitHub assets check failure for https://api.github.com/repos/doclayout_yolo/assets/releases/latest: 404 Not Found
Traceback (most recent call last):
  File "/home/zrway/llm/PDF-Extract-Kit/project/pdf2markdown/scripts/run_project.py", line 41, in <module>
    main(args.config)
  File "/home/zrway/llm/PDF-Extract-Kit/project/pdf2markdown/scripts/run_project.py", line 21, in main
    task_instances = initialize_tasks_and_models(config)
  File "/home/zrway/llm/PDF-Extract-Kit/project/pdf2markdown/scripts/../../../pdf_extract_kit/utils/config_loader.py", line 42, in initialize_tasks_and_models
    model_instance = ModelClass(model_config)
  File "/home/zrway/llm/PDF-Extract-Kit/project/pdf2markdown/scripts/../../../pdf_extract_kit/tasks/layout_detection/models/yolo.py", line 34, in __init__
    self.model = YOLOv10(config['model_path'])
  File "/home/zrway/miniconda3/envs/pdf-extract-kit-1.0/lib/python3.10/site-packages/doclayout_yolo/models/yolov10/model.py", line 10, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "/home/zrway/miniconda3/envs/pdf-extract-kit-1.0/lib/python3.10/site-packages/doclayout_yolo/engine/model.py", line 144, in __init__
    self._load(model, task=task)
  File "/home/zrway/miniconda3/envs/pdf-extract-kit-1.0/lib/python3.10/site-packages/doclayout_yolo/engine/model.py", line 233, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "/home/zrway/miniconda3/envs/pdf-extract-kit-1.0/lib/python3.10/site-packages/doclayout_yolo/nn/tasks.py", line 807, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "/home/zrway/miniconda3/envs/pdf-extract-kit-1.0/lib/python3.10/site-packages/doclayout_yolo/nn/tasks.py", line 733, in torch_safe_load
    ckpt = torch.load(file, map_location="cpu")
  File "/home/zrway/miniconda3/envs/pdf-extract-kit-1.0/lib/python3.10/site-packages/ultralytics/utils/patches.py", line 86, in torch_load
    return _torch_load(*args, **kwargs)
  File "/home/zrway/miniconda3/envs/pdf-extract-kit-1.0/lib/python3.10/site-packages/torch/serialization.py", line 997, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/zrway/miniconda3/envs/pdf-extract-kit-1.0/lib/python3.10/site-packages/torch/serialization.py", line 444, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/zrway/miniconda3/envs/pdf-extract-kit-1.0/lib/python3.10/site-packages/torch/serialization.py", line 425, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'models/Layout/YOLO/doclayout_yolo_ft.pt'

**Comment by wufan-tb** [comment]
download our layout model and then try again: https://huggingface.co/opendatalab/PDF-Extract-Kit-1.0/blob/main/models/Layout/YOLO/doclayout_yolo_ft.pt

**Comment by paperClub-hub** [comment]
"""
pdf2markdown/scripts/run_project.py", line 41, in <module>
    main(args.config)
  File "/data2/private/quhongsen/remote_dev/dev/llms/agents_dev/PDF-Extract-Kit/project/pdf2markdown/scripts/run_project.py", line 21, in main
    task_instances = initialize_tasks_and_models(config)
  File "/data2/private/quhongsen/remote_dev/dev/llms/agents_dev/PDF-Extract-Kit/project/pdf2markdown/scripts/../../../pdf_extract_kit/utils/config_loader.py", line 42, in initialize_tasks_and_models
    model_instance = ModelClass(model_config)
  File "/data2/private/quhongsen/remote_dev/dev/llms/agents_dev/PDF-Extract-Kit/project/pdf2markdown/scripts/../../../pdf_extract_kit/tasks/formula_recognition/models/unimernet.py", line 31, in __init__
    self.model, self.vis_processor = self.load_model_and_processor()
  File "/data2/private/quhongsen/remote_dev/dev/llms/agents_dev/PDF-Extract-Kit/project/pdf2markdown/scripts/../../../pdf_extract_kit/tasks/formula_recognition/models/unimernet.py", line 41, in load_model_and_processo

raise RuntimeError("checkpoint url or path is invalid")
RuntimeError: checkpoint url or path is invalid

"""
