### ISSUE TITLE
Error running on MacOS 

### ISSUE THREAD

**Issue by RunshengZhu** [opendatalab/PDF-Extract-Kit#23]
Error when run with mps enabled  on M3 machine
`Traceback (most recent call last):
  File "/Users/helius/Workspace/experiment/jinghai_vision/doc_gen/doc_gen_demo/PDF-Extract-Kit/pdf_extract.py", line 124, in <module>
    layout_res = layout_model(image, ignore_catids=[])
  File "/Users/helius/Workspace/experiment/jinghai_vision/doc_gen/doc_gen_demo/PDF-Extract-Kit/modules/layoutlmv3/model_init.py", line 125, in __call__
    outputs = self.predictor(image)
  File "/Users/helius/anaconda3/envs/PEK/lib/python3.10/site-packages/detectron2/engine/defaults.py", line 319, in __call__
    predictions = self.model([inputs])[0]
  File "/Users/helius/anaconda3/envs/PEK/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/helius/anaconda3/envs/PEK/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/helius/Workspace/experiment/jinghai_vision/doc_gen/doc_gen_demo/PDF-Extract-Kit/modules/layoutlmv3/rcnn_vl.py", line 55, in forward
    return self.inference(batched_inputs)
  File "/Users/helius/Workspace/experiment/jinghai_vision/doc_gen/doc_gen_demo/PDF-Extract-Kit/modules/layoutlmv3/rcnn_vl.py", line 113, in inference
    features = self.backbone(input)
  File "/Users/helius/anaconda3/envs/PEK/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/helius/anaconda3/envs/PEK/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/helius/anaconda3/envs/PEK/lib/python3.10/site-packages/detectron2/modeling/backbone/fpn.py", line 139, in forward
    bottom_up_features = self.bottom_up(x)
  File "/Users/helius/anaconda3/envs/PEK/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/helius/anaconda3/envs/PEK/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/helius/Workspace/experiment/jinghai_vision/doc_gen/doc_gen_demo/PDF-Extract-Kit/modules/layoutlmv3/backbone.py", line 106, in forward
    return self.backbone.forward(
  File "/Users/helius/Workspace/experiment/jinghai_vision/doc_gen/doc_gen_demo/PDF-Extract-Kit/modules/layoutlmv3/layoutlmft/models/layoutlmv3/modeling_layoutlmv3.py", line 906, in forward
    visual_emb = self.forward_image(images)
  File "/Users/helius/Workspace/experiment/jinghai_vision/doc_gen/doc_gen_demo/PDF-Extract-Kit/modules/layoutlmv3/layoutlmft/models/layoutlmv3/modeling_layoutlmv3.py", line 785, in forward_image
    x = self.patch_embed(x, self.pos_embed[:, 1:, :] if self.pos_embed is not None else None)
  File "/Users/helius/anaconda3/envs/PEK/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/helius/anaconda3/envs/PEK/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/helius/Workspace/experiment/jinghai_vision/doc_gen/doc_gen_demo/PDF-Extract-Kit/modules/layoutlmv3/layoutlmft/models/layoutlmv3/modeling_layoutlmv3.py", line 71, in forward
    position_embedding = F.interpolate(position_embedding, size=(Hp, Wp), mode='bicubic')
  File "/Users/helius/anaconda3/envs/PEK/lib/python3.10/site-packages/torch/nn/functional.py", line 4073, in interpolate
    return torch._C._nn.upsample_bicubic2d(input, output_size, align_corners, scale_factors)
NotImplementedError: The operator 'aten::upsample_bicubic2d.out' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op.`

**Comment by myhloli** [comment]
pip3 install --pre torch torchvision --index-url https://download.pytorch.org/whl/nightly/cpu
试下用nightly版本的pytorch能不能正常使用mps加速

**Comment by JerryyrreJ** [comment]
> pip3 install --pre torch torchvision --index-url https://download.pytorch.org/whl/nightly/cpu 试下用nightly版本的pytorch能不能正常使用mps加速

可以了，一样的问题，我重装了nightly版本好了

**Comment by myhloli** [comment]
> > pip3 install --pre torch torchvision --index-url https://download.pytorch.org/whl/nightly/cpu 试下用nightly版本的pytorch能不能正常使用mps加速
> 
> 
> 
> 可以了，一样的问题，我重装了nightly版本好了

好的，我们会更新一下文档

**Comment by WingI9B1** [comment]
@myhloli 我在重装了nightly版本后从这个问题转换成了下面的问题：
```
Traceback (most recent call last):
  File "/opt/miniconda3/envs/MinerU/bin/magic-pdf", line 8, in <module>
    sys.exit(cli())
  File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/cli/magicpdf.py", line 325, in pdf_command
    do_parse(
  File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/cli/magicpdf.py", line 111, in do_parse
    pipe.pipe_analyze()
  File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/pipe/UNIPipe.py", line 31, in pipe_analyze
    self.model_list = doc_analyze(self.pdf_bytes, ocr=True)
  File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/model/doc_analyze_by_custom_model.py", line 65, in doc_analyze
    from magic_pdf.model.pdf_extract_kit import CustomPEKModel
  File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/model/pdf_extract_kit.py", line 16, in <module>
    from unimernet.common.config import Config
  File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/unimernet/__init__.py", line 18, in <module>
    from unimernet.tasks import *
  File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/unimernet/tasks/__init__.py", line 10, in <module>
    from unimernet.tasks.unimernet_train import UniMERNet_Train
  File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/unimernet/tasks/unimernet_train.py", line 11, in <module>
    from torchtext.data import metrics
  File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/torchtext/__init__.py", line 18, in <module>
    from torchtext import _extension  # noqa: F401
  File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/torchtext/_extension.py", line 64, in <module>
    _init_extension()
  File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/torchtext/_extension.py", line 58, in _init_extension
    _load_lib("libtorchtext")
  File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/torchtext/_extension.py", line 50, in _load_lib
    torch.ops.load_library(path)
  File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/torch/_ops.py", line 1355, in load_library
    ctypes.CDLL(path)
  File "/opt/miniconda3/envs/MinerU/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/torchtext/lib/libtorchtext.so, 0x0006): Symbol not found: __ZN3c105ErrorC1ENSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEES7_PKv
  Referenced from: <8349B302-A1C9-3870-AB5A-21A14A352BC2> /opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/torchtext/lib/libtorchtext.so
  Expected in:     <4B86EBDA-DDBB-3335-A2E4-3B0B1061A69A> /opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/torch/lib/libc10.dylib
```
torch各个版本是：
```
torch                     2.5.0.dev20240724
torchtext                 0.18.0
torchvision               0.20.0.dev20240724
```
处理器是`Apple M2 Pro`，系统版本最新稳定版`MacOS Sonoma 14.5 (23F79)`

**Comment by myhloli** [comment]
> @myhloli 我在重装了nightly版本后从这个问题转换成了下面的问题：
> 
> ```
> Traceback (most recent call last):
>   File "/opt/miniconda3/envs/MinerU/bin/magic-pdf", line 8, in <module>
>     sys.exit(cli())
>   File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
>     return self.main(*args, **kwargs)
>   File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/click/core.py", line 1078, in main
>     rv = self.invoke(ctx)
>   File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/click/core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>   File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/cli/magicpdf.py", line 325, in pdf_command
>     do_parse(
>   File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/cli/magicpdf.py", line 111, in do_parse
>     pipe.pipe_analyze()
>   File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/pipe/UNIPipe.py", line 31, in pipe_analyze
>     self.model_list = doc_analyze(self.pdf_bytes, ocr=True)
>   File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/model/doc_analyze_by_custom_model.py", line 65, in doc_analyze
>     from magic_pdf.model.pdf_extract_kit import CustomPEKModel
>   File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/model/pdf_extract_kit.py", line 16, in <module>
>     from unimernet.common.config import Config
>   File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/unimernet/__init__.py", line 18, in <module>
>     from unimernet.tasks import *
>   File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/unimernet/tasks/__init__.py", line 10, in <module>
>     from unimernet.tasks.unimernet_train import UniMERNet_Train
>   File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/unimernet/tasks/unimernet_train.py", line 11, in <module>
>     from torchtext.data import metrics
>   File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/torchtext/__init__.py", line 18, in <module>
>     from torchtext import _extension  # noqa: F401
>   File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/torchtext/_extension.py", line 64, in <module>
>     _init_extension()
>   File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/torchtext/_extension.py", line 58, in _init_extension
>     _load_lib("libtorchtext")
>   File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/torchtext/_extension.py", line 50, in _load_lib
>     torch.ops.load_library(path)
>   File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/torch/_ops.py", line 1355, in load_library
>     ctypes.CDLL(path)
>   File "/opt/miniconda3/envs/MinerU/lib/python3.10/ctypes/__init__.py", line 374, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: dlopen(/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/torchtext/lib/libtorchtext.so, 0x0006): Symbol not found: __ZN3c105ErrorC1ENSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEES7_PKv
>   Referenced from: <8349B302-A1C9-3870-AB5A-21A14A352BC2> /opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/torchtext/lib/libtorchtext.so
>   Expected in:     <4B86EBDA-DDBB-3335-A2E4-3B0B1061A69A> /opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/torch/lib/libc10.dylib
> ```
> 
> torch各个版本是：
> 
> ```
> torch                     2.5.0.dev20240724
> torchtext                 0.18.0
> torchvision               0.20.0.dev20240724
> ```
> 
> 处理器是`Apple M2 Pro`，系统版本最新稳定版`MacOS Sonoma 14.5 (23F79)`

torchtext版本与torch不匹配
参考：https://github.com/opendatalab/PDF-Extract-Kit/issues/38#issuecomment-2241065147

**Comment by lswang6** [comment]
的确无法在M3 Pro启用mps，安装了上述也不行。
