### ISSUE TITLE
window 提示 不支持

### ISSUE THREAD

**Issue by leixinstar** [opendatalab/PDF-Extract-Kit#37]
Traceback (most recent call last):
  File "D:\PDF-Extract-Kit\pdf_extract.py", line 123, in <module>
    mfd_res = mfd_model.predict(image, imgsz=img_size, conf=conf_thres, iou=iou_thres, verbose=True)[0]
  File "D:\anaconda3\pkgs\pdf\lib\site-packages\ultralytics\engine\model.py", line 437, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "D:\anaconda3\pkgs\pdf\lib\site-packages\ultralytics\engine\predictor.py", line 305, in setup_model
    device=select_device(self.args.device, verbose=verbose),
  File "D:\anaconda3\pkgs\pdf\lib\site-packages\ultralytics\utils\torch_utils.py", line 172, in select_device
    s += f"CPU ({get_cpu_info()})\n"
  File "D:\anaconda3\pkgs\pdf\lib\site-packages\ultralytics\utils\torch_utils.py", line 72, in get_cpu_info
    import cpuinfo  # pip install py-cpuinfo
  File "D:\anaconda3\pkgs\pdf\lib\site-packages\cpuinfo\__init__.py", line 3, in <module>
    from cpuinfo.cpuinfo import *
  File "D:\anaconda3\pkgs\pdf\lib\site-packages\cpuinfo\cpuinfo.py", line 2827, in <module>
    _check_arch()
  File "D:\anaconda3\pkgs\pdf\lib\site-packages\cpuinfo\cpuinfo.py", line 366, in _check_arch
    raise Exception("py-cpuinfo currently only works on X86 "
Exception: py-cpuinfo currently only works on X86 and some ARM/PPC/S390X/MIPS/RISCV CPUs.

**Comment by myhloli** [comment]
您的设备cpu是？

**Comment by leixinstar** [comment]
12th Gen Intel(R) Core(TM) i7-1260P

**Comment by myhloli** [comment]
看着像是依赖库py-cpuinfo不支持获取这个cpu的信息，可以试试   pip install --upgrade py-cpuinfo 更新一下版本

**Comment by leixinstar** [comment]
> 看着像是依赖库py-cpuinfo不支持获取这个cpu的信息，可以试试 pip install --upgrade py-cpuinfo 更新一下版本

已经安装最新的9.0版本，还是提示一样的错误。

**Comment by myhloli** [comment]
那可能要在 https://github.com/workhorsy/py-cpuinfo 项目提一下issue看看能否修复这个问题。
