### ISSUE TITLE
Cannot run on Mac M-chip

### ISSUE THREAD

**Issue by bookandlover** [opendatalab/PDF-Extract-Kit#38]
Errors as the following:

(.venv) (base) pengxiong@PENGMacPro PDF-Extract-Kit % python pdf_extract.py --pdf demo/demo1.pdf
[2024-07-19 20:17:51,713] [   ERROR] check_version.py:39 - Error fetching version info
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 976, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1455, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1075, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pengxiong/LLM/PDF-Extract-Kit/.venv/lib/python3.11/site-packages/albumentations/check_version.py", line 29, in fetch_version_info
    with opener.open(url, timeout=2) as response:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)>
Traceback (most recent call last):
  File "/Users/pengxiong/LLM/PDF-Extract-Kit/pdf_extract.py", line 18, in <module>
    from unimernet.common.config import Config
  File "/Users/pengxiong/LLM/PDF-Extract-Kit/.venv/lib/python3.11/site-packages/unimernet/__init__.py", line 18, in <module>
    from unimernet.tasks import *
  File "/Users/pengxiong/LLM/PDF-Extract-Kit/.venv/lib/python3.11/site-packages/unimernet/tasks/__init__.py", line 10, in <module>
    from unimernet.tasks.unimernet_train import UniMERNet_Train
  File "/Users/pengxiong/LLM/PDF-Extract-Kit/.venv/lib/python3.11/site-packages/unimernet/tasks/unimernet_train.py", line 11, in <module>
    from torchtext.data import metrics
  File "/Users/pengxiong/LLM/PDF-Extract-Kit/.venv/lib/python3.11/site-packages/torchtext/__init__.py", line 18, in <module>
    from torchtext import _extension  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pengxiong/LLM/PDF-Extract-Kit/.venv/lib/python3.11/site-packages/torchtext/_extension.py", line 64, in <module>
    _init_extension()
  File "/Users/pengxiong/LLM/PDF-Extract-Kit/.venv/lib/python3.11/site-packages/torchtext/_extension.py", line 58, in _init_extension
    _load_lib("libtorchtext")
  File "/Users/pengxiong/LLM/PDF-Extract-Kit/.venv/lib/python3.11/site-packages/torchtext/_extension.py", line 50, in _load_lib
    torch.ops.load_library(path)
  File "/Users/pengxiong/LLM/PDF-Extract-Kit/.venv/lib/python3.11/site-packages/torch/_ops.py", line 1354, in load_library
    ctypes.CDLL(path)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: dlopen(/Users/pengxiong/LLM/PDF-Extract-Kit/.venv/lib/python3.11/site-packages/torchtext/lib/libtorchtext.so, 0x0006): Symbol not found: __ZN3c105ErrorC1ENSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEES7_PKv
  Referenced from: <5436ECC1-6F45-386E-B542-D5F76A22B52C> /Users/pengxiong/LLM/PDF-Extract-Kit/.venv/lib/python3.11/site-packages/torchtext/lib/libtorchtext.so
  Expected in:     <E3245DE7-CE84-3359-A48F-EFC60527A2BF> /Users/pengxiong/LLM/PDF-Extract-Kit/.venv/lib/python3.11/site-packages/torch/lib/libc10.dylib

**Comment by vonlaughing** [comment]
I encountered the same problem, this was after I performed the following steps:
<img width="1059" alt="image" src="https://github.com/user-attachments/assets/dda5aaaf-22b1-4095-a188-0c50a894b149">
<img width="575" alt="image" src="https://github.com/user-attachments/assets/d60ba799-4624-4c8a-8ee7-166ea4530ea2">

**Comment by myhloli** [comment]
> I encountered the same problem, this was after I performed the following steps:
> 
> <img width="1059" alt="image" src="https://github.com/user-attachments/assets/dda5aaaf-22b1-4095-a188-0c50a894b149">
> 
> <img width="575" alt="image" src="https://github.com/user-attachments/assets/d60ba799-4624-4c8a-8ee7-166ea4530ea2">
> 
> 
> 
> 

don't mind this error,you can try to run it.

**Comment by vonlaughing** [comment]
> > I encountered the same problem, this was after I performed the following steps:
> > <img alt="image" width="1059" src="https://private-user-images.githubusercontent.com/38173379/350678472-dda5aaaf-22b1-4095-a188-0c50a894b149.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NjY5NzEsIm5iZiI6MTcyMTQ2NjY3MSwicGF0aCI6Ii8zODE3MzM3OS8zNTA2Nzg0NzItZGRhNWFhYWYtMjJiMS00MDk1LWExODgtMGM1MGE4OTRiMTQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDA5MTExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0YWRhZjA1MGY5MDBhNTcxOTkxNGI0NmEwNmVhZWIyMzQwYWJhNjMxODJiMzU0YjVjNzdmMmMyYmZlMWZkYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.leHixAwwRugMPVF7cm5R3z6SyAQ_PEfC4VSIl2twYkY">
> > <img alt="image" width="575" src="https://private-user-images.githubusercontent.com/38173379/350678501-d60ba799-4624-4c8a-8ee7-166ea4530ea2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NjY5NzEsIm5iZiI6MTcyMTQ2NjY3MSwicGF0aCI6Ii8zODE3MzM3OS8zNTA2Nzg1MDEtZDYwYmE3OTktNDYyNC00YzhhLThlZTctMTY2ZWE0NTMwZWEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDA5MTExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3MTA5OWM5MjQ5ODgxZmM5MzJiZTY3ZDc0OWIxNDgyYTEzNThhNTRiNWE2YTBjZDZhMTkwMzc4Y2I4MTFmMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DpCnCpkRYtUn-BQjrtZOzJl9l8GCByz-K4X9nhEQRUk">
> 
> don't mind this error,you can try to run it.

When I run it I'm getting the following error:
<img width="562" alt="image" src="https://github.com/user-attachments/assets/ef940a00-1dae-410a-8b28-de1a6bbe1d8e">

Can you help me? Thank you!

**Comment by myhloli** [comment]
> OSError: dlopen(/Users/pengxiong/LLM/PDF-Extract-Kit/.venv/lib/python3.11/site-packages/torchtext/lib/libtorchtext.so, 0x0006): Symbol not found: __ZN3c105ErrorC1ENSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEES7_PKv

>TorchText development is stopped and the 0.18 release (April 2024) will be the last stable release of the library.

The versions of torch, torchvision, and torchtext need to be compatible. but torchtext 0.18.0 not compatibility of torch 2.5.0
maybe you can 
```bash
pip uninstall torch torchvision torchtext
pip install --pre torch torchvision torchtext --index-url https://download.pytorch.org/whl/nightly/cpu
```
to try use the nightly build to open mps, or
```bash
pip uninstall torch torchvision torchtext
pip install torch torchvision torchtext 
```
you can try using mps for this, if that's not possible, the cpu will work as well.

**Comment by vonlaughing** [comment]
Thank you! However this gets me here, I'm just gonna try the cpu version, thank you!
<img width="565" alt="image" src="https://github.com/user-attachments/assets/fb3e5f02-42f3-4796-a935-50d2186fd5d1">

**Comment by myhloli** [comment]
> Thank you! However this gets me here, I'm just gonna try the cpu version, thank you!
> 
> <img width="565" alt="image" src="https://github.com/user-attachments/assets/fb3e5f02-42f3-4796-a935-50d2186fd5d1">
> 
> 

As a temporary fix, you can set the environment var
iable 'PYTORCH_ENABLE_MPS_FALLBACK=1' to use the CPU as a fallback for this op.

**Comment by bookandlover** [comment]
<img width="1422" alt="image" src="https://github.com/user-attachments/assets/f5d04e14-9643-4d26-947c-a46672156ca2">
Solved after many tries. The problem comes from certifi update. Refer:
这个错误是由于权限不足导致无法更新 `certifi` 包。你需要使用管理员权限来运行该命令。可以尝试以下步骤来解决这个问题：

### 1. 使用 `sudo` 命令

在终端中运行以下命令，使用 `sudo` 提升权限来安装 `certifi`：

```sh
sudo /Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11 -m pip install --upgrade certifi
```

系统会提示你输入管理员密码，输入密码后继续安装。

### 2. 更新 `pip`

更新 `pip` 版本可能会有助于解决问题。使用以下命令来更新 `pip`：

```sh
sudo /Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11 -m pip install --upgrade pip
```

然后再尝试升级 `certifi`：

```sh
sudo /Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11 -m pip install --upgrade certifi
```

### 3. 验证安装

成功安装 `certifi` 后，运行以下命令验证安装是否成功：

```sh
/Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11 -m pip show certifi
```

### 4. 重新运行证书安装脚本

再次运行证书安装脚本：

```sh
/Applications/Python\ 3.11/Install\ Certificates.command
```

如果上述步骤完成后没有错误，请重新运行你的 `pdf_extract.py` 脚本：

```sh
python pdf_extract.py --pdf demo/demo1.pdf
```

这样应该能够解决证书和权限相关的问题。如果仍有其他问题，请告诉我详细信息。

**Comment by myhloli** [comment]
@bookandlover Thank you for your feedback. We will update the document so that other users can solve similar problems.

**Comment by bookandlover** [comment]
在PDF文件提取中遇到无法启动MPS的问题，需要强制退回到CPU执行。很可能的原因是特定版本的 PyTorch 和 detectron2 之间存在兼容性问题，尝试降级或升级它们以解决问题。能否给出正确的版本号呢？我是M2 ULTRA的芯片。下面是一段示意代码。非常感谢。

pip install torch==1.12.1 torchvision==0.13.1
pip install detectron2==0.6 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu113/torch1.12/index.html

**Comment by myhloli** [comment]
> 在PDF文件提取中遇到无法启动MPS的问题，需要强制退回到CPU执行。很可能的原因是特定版本的 PyTorch 和 detectron2 之间存在兼容性问题，尝试降级或升级它们以解决问题。能否给出正确的版本号呢？我是M2 ULTRA的芯片。下面是一段示意代码。非常感谢。
> 
> 
> 
> pip install torch==1.12.1 torchvision==0.13.1
> 
> pip install detectron2==0.6 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu113/torch1.12/index.html

pip install torch==2.3.1 torchvision==0.18.1 torchtext==0.18.0 

pip install detectron2 --extra-index-url https://myhloli.github.io/wheels/

for python 3.10 it works good

**Comment by dennicLiu** [comment]
Error: command buffer exited with error status.
        The Metal Performance Shaders operations encoded on it may not have completed.
        Error: 
        (null)
        Internal Error (0000000e:Internal Error)
        <AGXG14XFamilyCommandBuffer: 0x37ba4f2c0>
    label = <none> 
    device = <AGXG14SDevice: 0x30888a600>
        name = Apple M2 Pro 
    commandQueue = <AGXG14XFamilyCommandQueue: 0x32128f200>
        label = <none> 
        device = <AGXG14SDevice: 0x30888a600>
            name = Apple M2 Pro 
    retainedReferences = 1
Error: command buffer exited with error status.
        The Metal Performance Shaders operations encoded on it may not have completed.
        Error: 
        (null)
        Internal Error (0000000e:Internal Error)
        <AGXG14XFamilyCommandBuffer: 0x37ba4ed50>
    label = <none> 
    device = <AGXG14SDevice: 0x30888a600>
        name = Apple M2 Pro 
    commandQueue = <AGXG14XFamilyCommandQueue: 0x32128f200>
        label = <none> 
        device = <AGXG14SDevice: 0x30888a600>
            name = Apple M2 Pro 
    retainedReferences = 1
Error: command buffer exited with error status.
        The Metal Performance Shaders operations encoded on it may not have completed.
        Error: 
        (null)
        Internal Error (0000000e:Internal Error)
        <AGXG14XFamilyCommandBuffer: 0x37ba50af0>
    label = <none> 
    device = <AGXG14SDevice: 0x30888a600>
        name = Apple M2 Pro 
    commandQueue = <AGXG14XFamilyCommandQueue: 0x32128f200>
        label = <none> 
        device = <AGXG14SDevice: 0x30888a600>
            name = Apple M2 Pro 
    retainedReferences = 1
Error: command buffer exited with error status.
        The Metal Performance Shaders operations encoded on it may not have completed.
        Error: 
        (null)
        Internal Error (0000000e:Internal Error)
        <AGXG14XFamilyCommandBuffer: 0x37ba4c5d0>
    label = <none> 
    device = <AGXG14SDevice: 0x30888a600>
        name = Apple M2 Pro 
    commandQueue = <AGXG14XFamilyCommandQueue: 0x32128f200>
        label = <none> 
        device = <AGXG14SDevice: 0x30888a600>
            name = Apple M2 Pro 
    retainedReferences = 1
Traceback (most recent call last):
  File "/Users/liuchuang/Desktop/engram/PDF-Extract-Kit/pdf_extract.py", line 123, in <module>
    layout_res = layout_model(image, ignore_catids=[])
  File "/Users/liuchuang/Desktop/engram/PDF-Extract-Kit/modules/layoutlmv3/model_init.py", line 124, in __call__
    outputs = self.predictor(image)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/test1/lib/python3.10/site-packages/detectron2/engine/defaults.py", line 319, in __call__
    predictions = self.model([inputs])[0]
  File "/opt/homebrew/Caskroom/miniconda/base/envs/test1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/test1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/liuchuang/Desktop/engram/PDF-Extract-Kit/modules/layoutlmv3/rcnn_vl.py", line 55, in forward
    return self.inference(batched_inputs)
  File "/Users/liuchuang/Desktop/engram/PDF-Extract-Kit/modules/layoutlmv3/rcnn_vl.py", line 122, in inference
    results, _ = self.roi_heads(images, features, proposals, None)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/test1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/test1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/test1/lib/python3.10/site-packages/detectron2/modeling/roi_heads/cascade_rcnn.py", line 150, in forward
    pred_instances = self.forward_with_given_boxes(features, pred_instances)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/test1/lib/python3.10/site-packages/detectron2/modeling/roi_heads/roi_heads.py", line 776, in forward_with_given_boxes
    instances = self._forward_mask(features, instances)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/test1/lib/python3.10/site-packages/detectron2/modeling/roi_heads/roi_heads.py", line 843, in _forward_mask
    features = self.mask_pooler(features, boxes)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/test1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/test1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/test1/lib/python3.10/site-packages/detectron2/modeling/poolers.py", line 243, in forward
    pooler_fmt_boxes = convert_boxes_to_pooler_format(box_lists)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/test1/lib/python3.10/site-packages/detectron2/modeling/poolers.py", line 98, in convert_boxes_to_pooler_format
    return _convert_boxes_to_pooler_format(boxes, sizes)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/test1/lib/python3.10/site-packages/torch/jit/_trace.py", line 1254, in wrapper
    return fn(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/test1/lib/python3.10/site-packages/detectron2/modeling/poolers.py", line 66, in _convert_boxes_to_pooler_format
    indices = torch.repeat_interleave(
RuntimeError: Expected repeatBuffer && cumsumBuffer && resultBuffer to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
