### ISSUE TITLE
最近mac和Linux安装都有问题

### ISSUE THREAD

**Issue by Joker1212** [opendatalab/PDF-Extract-Kit#62]
上一周在windows上运行稳定，最近使用Mac时，遇到了安装的问题，首先是
，然后执行了
<img width="975" alt="image" src="https://github.com/user-attachments/assets/49c2aada-4a1d-4f08-a955-f5b126b4a28d">
接着遇到了
Traceback (most recent call last):
  File "/home/featurize/work/pdf-extractor/pdf_extract.py", line 18, in <module>
    from unimernet.common.config import Config
  File "/environment/miniconda3/lib/python3.11/site-packages/unimernet/__init__.py", line 18, in <module>
    from unimernet.tasks import *
  File "/environment/miniconda3/lib/python3.11/site-packages/unimernet/tasks/__init__.py", line 10, in <module>
    from unimernet.tasks.unimernet_train import UniMERNet_Train
  File "/environment/miniconda3/lib/python3.11/site-packages/unimernet/tasks/unimernet_train.py", line 11, in <module>
    from torchtext.data import metrics
  File "/environment/miniconda3/lib/python3.11/site-packages/torchtext/__init__.py", line 18, in <module>
    from torchtext import _extension  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/environment/miniconda3/lib/python3.11/site-packages/torchtext/_extension.py", line 64, in <module>
    _init_extension()
  File "/environment/miniconda3/lib/python3.11/site-packages/torchtext/_extension.py", line 58, in _init_extension
    _load_lib("libtorchtext")
  File "/environment/miniconda3/lib/python3.11/site-packages/torchtext/_extension.py", line 50, in _load_lib
    torch.ops.load_library(path)
  File "/environment/miniconda3/lib/python3.11/site-packages/torch/_ops.py", line 1361, in load_library
    ctypes.CDLL(path)
  File "/environment/miniconda3/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /environment/miniconda3/lib/python3.11/site-packages/torchtext/lib/libtorchtext.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs
因为在安装detect2的时候ssl无法拉取whl，所以直接下载了whl进行安装,但是依然无法解决，然后我尝试去看是否是模型有更新，发现在modelScope上最近一周也没有更新
<img width="621" alt="image" src="https://github.com/user-attachments/assets/3790bcab-dc54-43bc-927c-7896bf4bde40">

**Comment by Joker1212** [comment]
发现我的问题是因为下载模型的时候，中途停止了，未检查模型的大小，其实是我的问题，对不起
