### ISSUE TITLE
paddlepaddle报错

### ISSUE THREAD

**Issue by shenjunyu57** [opendatalab/PDF-Extract-Kit#77]
您好，我运行代码时遇到了如下错误，
 Traceback (most recent call last):
  File "/raid/shnu/sjy/PDF-Extract-Kit-main/pdf_extract.py", line 186, in <module>
    ocr_res = ocr_model.ocr(cropped_img, mfd_res=single_page_mfdetrec_res)[0]
  File "/raid/shnu/sjy/PDF-Extract-Kit-main/modules/self_modify.py", line 165, in ocr
    dt_boxes, rec_res, _ = self.__call__(img, cls, mfd_res=mfd_res)
  File "/raid/shnu/sjy/PDF-Extract-Kit-main/modules/self_modify.py", line 210, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "/raid/shnu/miniconda3/envs/pipe/lib/python3.10/site-packages/paddleocr/tools/infer/predict_det.py", line 244, in __call__
    self.input_tensor.copy_from_cpu(img)
  File "/raid/shnu/miniconda3/envs/pipe/lib/python3.10/site-packages/paddle/inference/wrapper.py", line 52, in tensor_copy_from_cpu
    self._copy_from_cpu_bind(data)
RuntimeError: (PreconditionNotMet) Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion.
  [Hint: cudnn_dso_handle should not be null.] (at ../paddle/phi/backends/dynload/cudnn.cc:76)

nvcc版本：
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

cudnn版本为 8.9.2.26

请问该怎么解决

**Comment by ouyanglinke** [comment]
You need to add LD_LIBRARY_PATH in your ~/.bashrc. Check this: https://github.com/PaddlePaddle/Paddle/issues/30694
