### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'v'. 错误

### ISSUE THREAD

**Issue by 724852499** [opendatalab/PDF-Extract-Kit#90]
root@ca9782e90bf9:/home/pdf/PDF-Extract-Kit# python pdf_extract.py --pdf /home/pdf/test.pdf
Namespace(pdf='/home/pdf/test.pdf', output='output', vis=False, render=False)
2024-08-15 17:08:10
Started!
Traceback (most recent call last):
  File "/home/pdf/PDF-Extract-Kit/pdf_extract.py", line 98, in <module>
    mfd_model = mfd_model_init(model_configs['model_args']['mfd_weight'])
  File "/home/pdf/PDF-Extract-Kit/pdf_extract.py", line 31, in mfd_model_init
    mfd_model = YOLO(weight)
  File "/usr/local/lib/python3.10/site-packages/ultralytics/models/yolo/model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "/usr/local/lib/python3.10/site-packages/ultralytics/engine/model.py", line 142, in __init__
    self._load(model, task=task)
  File "/usr/local/lib/python3.10/site-packages/ultralytics/engine/model.py", line 294, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "/usr/local/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 855, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "/usr/local/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 781, in torch_safe_load
    ckpt = torch.load(file, map_location="cpu")
  File "/usr/local/lib/python3.10/site-packages/ultralytics/utils/patches.py", line 86, in torch_load
    return _torch_load(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.10/site-packages/torch/serialization.py", line 1262, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
执行命令报错，什么原因呢

**Comment by myhloli** [comment]
模型下载不完整，请检查模型文件大小和网页上是否一致，如果大小一致，可以进一步通过sha256确认是否下载完整。

**Comment by 724852499** [comment]
重新删除 下载还是有这个问题，能告知是哪个模型出错呢

**Comment by myhloli** [comment]
> 重新删除 下载还是有这个问题，能告知是哪个模型出错呢

通过文件大小比对一下呢？大小不一致的就是有问题的

**Comment by 724852499** [comment]
![image](https://github.com/user-attachments/assets/7e3dab85-30fa-42af-8da1-aa1d52dffa4a)

**Comment by myhloli** [comment]
> ![image](https://private-user-images.githubusercontent.com/40465127/358181294-7e3dab85-30fa-42af-8da1-aa1d52dffa4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MTQ1MDgsIm5iZiI6MTcyMzcxNDIwOCwicGF0aCI6Ii80MDQ2NTEyNy8zNTgxODEyOTQtN2UzZGFiODUtMzBmYS00MmFmLThkYTEtYWExZDUyZGZmYTRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDA5MzAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkYzEzYjk2OWU2YTE2Yzk1MzIxYzk3NWZlMzZjZGNhMDY1YWE4OThlMjc0ODFjNGI2OTY3MTdhZmI0MWY5YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FwdnGrj0zErYSukdsLzCBXLRlJh_jX25t2U1yLoHPi0)

大小太小了，确认下自己是不是没安装git lfs

**Comment by 724852499** [comment]
可以下载了，下载下来有点大啊，磁盘都装不下了，模型有多大呢，是必须全不下载还是可以选择一部分模型呢

**Comment by myhloli** [comment]
约6GB，需要全部下载

**Comment by 724852499** [comment]
![image](https://github.com/user-attachments/assets/1ca01314-6e2d-4737-9e35-81ba01a89414)
![image](https://github.com/user-attachments/assets/cd348c1b-4f36-48b5-92d3-a9c7fe62c891)
模型下载下来了，但提取这个错呢，是下载的模型有问题呢？

**Comment by 724852499** [comment]
下完整了，后面发现是内存不够加载模型报的错误信息

**Comment by 724852499** [comment]
如果只想使用cpu，不使用gpu,需要怎么操作呢

**Comment by myhloli** [comment]
> 如果只想使用cpu，不使用gpu,需要怎么操作呢

参考这个文档：https://github.com/opendatalab/PDF-Extract-Kit/blob/main/docs/Install_in_Windows_zh_cn.md#3修改config-使用cpu推理
修改两个地方的cuda为cpu

**Comment by 724852499** [comment]
好的，十分感谢

**Comment by Neverthless** [comment]
整个文件有接近7个G，但其中layout为什么就几kb，我是在跑layout的时候遇到的这个问题
